---
- name: "Index items from CSV to Elasticsearch"
  hosts: localhost
  gather_facts: no
  vars:
    mylist:
      type: fruit
      ttl: 60m
      country: US
  tasks:
    # - name: Read data from CSV file
    #   set_fact:
    #     csv_data: "{{ lookup('csvfile', 'hosts.csv', delimiter=',') }}"

    - name: "Read as a list"
      read_csv:
        path: ./hosts.csv
      register: csv_data

    - set_fact:
        bulk_msg: >
          {%- for item in csv_data.list -%}
              {"index": {"_index": "TEST", "_type": "_doc"} }
              \n{{ item | to_nice_json }}
              \n
          {%- endfor -%}

    - debug:
        var: bulk_msg

    - name: "Read as a list"
      read_csv:
        path: ./hosts.csv
      register: csv_data

    - set_fact:
        csv_data_with_concatenated_column: >-
          {%- set updated_list = [] -%}
          {%- for item in csv_data.list -%}
            {%- set _ = updated_list.append(item | combine({'new_column': item.hostname ~ "-" ~ item.destination_ip})) -%}
          {%- endfor -%}
          {{ updated_list }}
    - debug:
        msg: "{{ csv_data_with_concatenated_column }}"


    # - set_fact:
    #     bulk_msg: >
    #           {%- for item in csv_data.list -%}
    #           { "index" : { "_index" : "TEST", "_type" : "_doc" } }
    #           { "hostname" : "{{ item.0 }}", "your_field_name_2" : "{{ item.1 }}", "your_field_name_3" : "{{ item.2 }}" }
    #           {%- if not loop.last -%}
    #           \n
    #           {%- endif -%}
    #           {%- endfor -%}

    # - debug:
    #     msg: "{{bulk_msg}}"
        # - name: Index data to Elasticsearch
        #   uri:
        #     url: "http://your_elasticsearch_host:9200/your_index_name/_bulk"
        #     method: POST
        #     body_format: json
        #     body: |
        #       {%- for item in csv_data -%}
        #       { "index" : { "_index" : "your_index_name", "_type" : "_doc" } }
        #       { "your_field_name_1" : "{{ item.0 }}", "your_field_name_2" : "{{ item.1 }}", "your_field_name_3" : "{{ item.2 }}" }
        #       {%- if not loop.last -%}
        #       \n
        #       {%- endif -%}
        #       {%- endfor -%}
        #     status_code: 200
        #     headers:
        #       Content-Type: "application/json"
        #   register: result

        # - debug:
        #     var: result
